### ISSUE TITLE
is_valid_for_data should be staticmethod, not classmethod

### ISSUE THREAD

**Issue by mossberg** [trailofbits/ethersplay#11]
https://github.com/trailofbits/ethersplay/blob/d638ae558ffbd705f0c20ccd1b76e67bae1d7e4d/ethersplay/evm.py#L444

minor, but `is_valid_for_data` is currently a classmethod, but it should probably be a staticmethod, since it doesn't instantiate an EVMView, and doesn't require access to the `self` object.

**Comment by computerality** [comment]
This matches with the binja examples https://github.com/Vector35/binaryninja-api/search?l=Python&q=is_valid_for_data&type= but maybe those should be changed too

**Comment by joshwatson** [comment]
This was done in the refactor, now in master
