### ISSUE TITLE
Replace old EVMInstruction with manticore's new EVMAsm

### ISSUE THREAD

**Issue by computerality** [trailofbits/ethersplay#14]

**Comment by montyly** [comment]
See the `manticore_integration` branch: https://github.com/trailofbits/ethersplay/blob/e80ca243487162e6ef484a159bd8a87ece74558f/ethersplay/evm.py#L1

Though at the time of writing this branch, binja needed some fixes to be able to load manticore. Further tests are required to be sure that binja can load manticore without error.

**Comment by joshwatson** [comment]
Completed in master. I do think that the EVMAsm python script should be moved to its own repo and submoduled by everything that is using it at some point though (manticore, ida-evm, ethersplay, etc)
