### ISSUE TITLE
Manticore coverage fails

### ISSUE THREAD

**Issue by fergarrui** [trailofbits/ethersplay#19]
I tried to use ethersplay with manticore and I could not make it work.

* I downloaded the latest version of Binary Ninja, Ethersplay and manticore.
* I used the example contract you have in the Readme (Test.sol),
* I compiled the contract, got the runtime-bin, saved it as test.evm (adding 0x as prefix)
* I open the file in Binary Ninja, the correct graph is displayed, everyone is happy.
* I run `manticore Test.sol` and a new directory is created. Looks fine.
* I right click->EVM Manticore Highlight, and I open the `visited.txt` file as stated in the Readme.
* Nothing happens, an error is shown in the log:

```
Traceback (most recent call last):
  File "/home/test/binary/binaryninja/plugins/../python/binaryninja/plugin.py", line 88, in _default_action
    action(view_obj)
  File "/home/test/.binaryninja/plugins/ethersplay/coverage.py", line 37, in function_coverage_start
    colorer.color(visited)
  File "/home/test/.binaryninja/plugins/ethersplay/coverage.py", line 20, in color
    self.color_at(int(addr, 16))
  File "/home/test/.binaryninja/plugins/ethersplay/coverage.py", line 29, in color_at
    func.set_instr_highlight(addr, blue)
AttributeError: 'Function' object has no attribute 'set_instr_highlight'
```

**Comment by montyly** [comment]
Thank you for the report, indeed a bug was recently introduced. It should be fixed in master now.

Note that you can also only highlight one particular execution trace by opening a `*.trace` file instead of the `visited.txt` file.

**Comment by fergarrui** [comment]
Tested and works perfectly now. Thanks a lot for the quick fix!
