### ISSUE TITLE
Ethersplay does not restore analysis / CFG / exploration from saved BNDB

### ISSUE THREAD

**Issue by gaasedelen** [trailofbits/ethersplay#24]
After correctly loading and analyzing an evm bytecode file with BinaryNinja + Ethersplay, the plugin doesn't save its exploration results/analysis to the BNDB when saved to disk. This makes it difficult to persist reversing notes or research for larger contracts spanning multiple sessions.

To repro, simply open any valid bytecode file with BinaryNinja + Ethersplay, let the analysis complete, and save the resulting BNDB to disk. When reopening the saved BNDB from disk, you will find that no exploration data, function definitions (etc...) have been saved to disk.

**Comment by joshwatson** [comment]
This should be fixed in master now
