### ISSUE TITLE
Jumpdests in immediates should be treated as invalid

### ISSUE THREAD

**Issue by itsZN** [trailofbits/ethersplay#29]
EVM does not allow jumping to jumpdests that happen to be in immediate values (ie pushed values).

For example something like this contract.
```
pragma solidity ^0.4.0;
contract Jump {
    function test() public {
        assembly {
            let b := add(0x5b604160425500,1)
            jump(0x5a)
        }
    }
}
```

When calling test(), EVM will *always* throw when it tries to execute the jump. However ethersplay shows it falling though to the embedded code:

![](https://itszn.com/u/da97684708f9dd5488a8b4015a883f7dd565bbb6.png)

[Geth makes a bitmap of all valid jumpdests](https://github.com/ethereum/go-ethereum/blob/master/core/vm/analysis.go) to determine if any jumpdests are in immediate values.

Code in this form probably won't be generated naturally, but it could be used for obfuscation. By jumping into a function hash in the dispatch (like my recent challenge did), I was able to confuse ethersplay into producing a loop and being unable to identify the dispatched functions:

![](https://itszn.com/u/981c40dd0ef46b6be6dcd52b208af68dae505d22.png)

(I use a function `aekS()` which hashes to 0x5b61291c, `jumpdest; push2 XX`)

**Comment by joshwatson** [comment]
I pushed a fix for this to the RewriteStackValue branch; it definitely fixes the example contract.
