### ISSUE TITLE
How do I hide variable names?

### ISSUE THREAD

**Issue by poma** [trailofbits/ethersplay#32]
On the screenshot there are no var names: 

![screen](https://github.com/trailofbits/ethersplay/raw/master/images/example.png)

but on my machine it looks like this:

<img width="236" alt="screen shot 2018-05-18 at 03 15 07" src="https://user-images.githubusercontent.com/2109710/40209736-b2d61dda-5a49-11e8-8ec9-a1d0aa037c20.png">

How do I disable those `{var_...}` thingies?

**Comment by withzombies** [comment]
You can't hide the variable names.

The screenshot is old. We rewrote the analysis to use more Binary Ninja APIs and the variables are a byproduct of that.

**Comment by poma** [comment]
And there is no easy way to hide them by commenting out a part of code?

**Comment by withzombies** [comment]
No, it was a pretty massive rewrite. The rewrite allows ethersplay databases to be saved and reopened, as well as enables better stack value analysis. 

You might have luck poking the [Binary Ninja](https://github.com/Vector35/binaryninja-api/issues) people. They could provide an option to disable annotations.

**Comment by poma** [comment]
ok thx
